---
layout: post
title: "行人重识别(ReID) ——数据集描述 DukeMTMC-reID"
date:   2023-07-08
tags: [DukeMTMC,reID,txt,bounding,box]
comments: true
author: admin
---
# 行人重识别(ReID) ——数据集描述 DukeMTMC-reID

## 数据集简介

DukeMTMC-reID 是 DukeMTMC 数据集的行人重识别子集，提供了人工标注的 bounding box。DukeMTMC 数据集是一个大规模标记的多目标多摄像机行人跟踪数据集，由 8 个同步摄像机记录，包含 7,000 多个单摄像机轨迹和超过 2,700 多个独立人物。

## 目录结构

```
DukeMTMC-reID
├── bounding_box_test
├── bounding_box_train
├── query
└── CITATION_DukeMTMC.txt
└── CITATION_DukeMTMC-reID.txt
└── LICENSE_DukeMTMC.txt
└── LICENSE_DukeMTMC-reID.txt
└── README.md
```

## 目录介绍

- **bounding_box_test**: 用于测试集的 702 人，包含 17,661 张图像（随机采样，702 ID + 408 distractor ID）。
- **bounding_box_train**: 用于训练集的 702 人，包含 16,522 张图像（随机采样）。
- **query**: 为测试集中的 702 人在每个摄像头中随机选择一张图像作为 query，共有 2,228 张图像。
- **CITATION_DukeMTMC.txt**: 引用 DukeMTMC 数据集的参考文献。
- **CITATION_DukeMTMC-reID.txt**: 引用 DukeMTMC-reID 数据集的参考文献。
- **LICENSE_DukeMTMC.txt**: DukeMTMC 数据集的许可证。
- **LICENSE_DukeMTMC-reID.txt**: DukeMTMC-reID 数据集的许可证。
- **README.md**: 本文件，介绍数据集的基本信息。

## 命名规则

以 `0001_c2_f0046182.jpg` 为例：
1. `0001` 表示每个人的标签编号。
2. `c2` 表示来自第二个摄像头(camera2)，共有 8 个摄像头。
3. `f0046182` 表示来自第二个摄像头的第 46182 帧。

## 数据分布

DukeMTMC-reID 训练集的图像分布中，每个 ID 的中位数为 20 张图像。但有些 ID 可能包含大量图像，这可能会影响某些算法。

## 测试协议

可以使用 Matlab 或 Python 进行评估。需要计算 gallery 和 query 的特征，并保存为矩阵。然后运行评估代码进行评估。

## 参考文献

如果您使用此数据集，请引用以下两篇论文：

1. Zheng, Zhedong, Zheng, Liang, and Yang, Yi. "Unlabeled Samples Generated by GAN Improve the Person Re-identification Baseline in vitro." Proceedings of the IEEE International Conference on Computer Vision, 2017.
2. Ristani, Ergys, Solera, Francesco, Zou, Roger, Cucchiara, Rita, and Tomasi, Carlo. "Performance Measures and a Data Set for Multi-Target, Multi-Camera Tracking." European Conference on Computer Vision workshop on Benchmarking Multi-Target Tracking, 2016.

## 下载链接

[行人重识别ReID数据集描述DukeMTMC-reID分享](https://pan.quark.cn/s/29731f073444)